version: '3'
services:
  db:
    container_name: db
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    env_file:
      - .env
    ports:
      - 3306
      - 33060
    volumes:
        - ./data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    ports:
      - 8088:80
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    volumes:
      - ./html:/var/www/html
    