version: '3'

services:
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    ports:
      - 3306
    volumes:
        - ./data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    env_file:
      - .env

  wordpress:
    image: wordpress:latest
    ports:
      - 8088:80
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    volumes:
      - ./html:/var/www/html
    logging:
      driver: splunk
      options:
        splunk-format: "raw"
        splunk-token: fe95216f-9897-422f-9eca-21827f2fa0d9
        splunk-url: https://3.90.105.35:8088/ 
        splunk-insecureskipverify: "true"
        labels: "WordPress"
        
        
    