version: '3'

services:
  db:
    container_name: db
    image: mysql:8.0.27
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    ports:
      - 3306
      - 33060

  wordpress:
    image: wordpress:latest
    ports:
      - 8088:80
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    volumes:
      - ./html:/var/www/html