version: '3'

services:
  db:
    container_name: db
    image: mysql:8.0.27
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    expose:
      - 3306
      - 33060
  phpmyadmin:
    depends_on:
        - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    env_file:
      - .env
  wordpress:
    image: wordpress:latest
    ports:
      - "8088:80"
    depends_on:
      - db
    restart: always
    env_file:
      - .env

    volumes:
      - ./html:/var/www/html