version: '3'

services:
  db:
    container_name: db
    image: mysql:8.0.27
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    # environment:
    #   - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
    #   - MYSQL_DATABASE:${MYSQL_DATABASE}
    #   - MYSQL_USER:${MYSQL_USER}
    #   - MYSQL_PASSWORD:${MYSQL_PASSWORD}
    expose:
      - 3306
      - 33060
  phpmyadmin:
    depends_on:
        - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    env_file:
      - .env
      # environment:
      #   PMA_HOST: db
      #   MYSQL_ROOT_PASSWORD: password   
  wordpress:
    image: wordpress:latest
    ports:
      - "8088:80"
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    # environment:
    #   - WORDPRESS_DB_HOST:${WORDPRESS_DB_HOST}
    #   - WORDPRESS_DB_USER:${WORDPRESS_DB_USER}
    #   - WORDPRESS_DB_PASSWORD:${WORDPRESS_DB_PASSWORD}
    #   - WORDPRESS_DB_NAME:${WORDPRESS_DB_NAME}
    volumes:
      - ./html:/var/www/html