version: '3'

services:
  splunk:
    container_name: splunk
    image: splunk/splunk:latest
    volumes:
      - ./splunk:/var/splunk
    restart: always
    env_file:
      - .env
    ports:
      -  8000:8000
      -  8087:8087
